#! /bin/bash

if [ $# -gt 1 ]; then
	echo "Usage: latest_commit [repo]"
	exit 1
fi

repo_path="${1-$(pwd)}"

echo -e "\e[1m$repo_path\e[m:"

if [ ! -e $repo_path ]; then
	echo "  [!] Directory not found."
	exit 2
fi

if [ ! -e $repo_path"/.git" ]; then
	echo "  [!] The directory is not git repository."
	exit 3
fi

cd $repo_path
echo -e "    Latest Commit: $(git log -1 --date=format:"%m/%d %H:%M" --pretty='\e[38;5;80m%s\e[m\e[38;5;243m<%h>\e[m (%cd)')"
echo -e "   Current Branch: \e[38;5;80;1m$(git symbolic-ref --short HEAD)\e[m"
