#!/bin/python3

import os
import random
import re
import sys

import yaml

from scripts.lib import args

MEIGEN_TEMPLATE = {
    "content": {
        False: "\033[38;5;229;1m   {0}\033[m",
        True: "{0}"
    },
    "prop": {
        False: "\033[38;5;250m               --- {0} (#{1})\033[m",
        True: "               --- {0} (#{1})"
    }
}

DEFAULT_FILE_PATH = \
    os.environ["BLINTOOL_DIRECTORY"] + \
    "/local_data/meigen.yaml"

argument: args.ArgParser = args.ArgParser(
    name="meigen_fortune",
    args=[
        args.FlagArgs(
            "no-color", "Show meigen without color.",
            dest="color"
        ),
        args.OptionContentArgs(
            "id", "The ID of the meigen you want to see.",
        ),
        args.PositionalArgs(
            "file", "The file to read meigen.",
            required=False
        )
    ]
)

if __name__ == '__main__':
    with open(argument.get_or("file", DEFAULT_FILE_PATH)) as f:
        meigen_db = yaml.load(f.read(), yaml.FullLoader)

    raw_meigen_id = argument.get_or(
        "id", str(random.randint(0, len(meigen_db) - 1))
    )

    if re.match("-?[0-9]+", raw_meigen_id) is None:
        print("[!] The Meigen ID seems not valid number.")
        sys.exit(1)

    meigen_id = int(raw_meigen_id)

    if not (1 <= meigen_id < len(meigen_db)):
        print(
            "[!] The Meigen ID is not in valid range(0 to {0}).".format(
                len(meigen_db)
            )
        )
        sys.exit(2)

    meigen = meigen_db[meigen_id - 1]
    print(MEIGEN_TEMPLATE["content"][argument.get_or("color", False)].format(
        meigen["content"].replace("\n", "\n   ")
    ))
    print(MEIGEN_TEMPLATE["prop"][argument.get_or("color", False)].format(
        meigen["author"], meigen["id"]
    ))
